'use strict';
/**
 * catalog.config.cjs — the curated catalogue of pre-rendered séances.
 *
 * Each entry is one sitting that gets generated by Opus and voiced by Edge-TTS
 * into MP3 clips under public/seances/<id>/. French-first; a handful of English
 * sittings round it out. Pacing is balanced (0) across the catalogue.
 *
 * To grow the catalogue: add an entry with a NEW, stable `id`, then run
 *   npm run render:seances
 * The render is idempotent — existing ids are skipped unless --force.
 *
 * id MUST be filesystem- and URL-safe and STABLE (it's the asset folder name).
 */

/** @type {{id:string, theme:string, register:string, length:number, lang:string, pacing?:number}[]} */
const CATALOG = [
  // ── French (primary) ──────────────────────────────────────────────────────
  { id: 'fr-focus-plain-5', theme: 'focus', register: 'plain', length: 5, lang: 'fr' },
  { id: 'fr-focus-stoic-3', theme: 'focus', register: 'stoic', length: 3, lang: 'fr' },
  { id: 'fr-sleep-poetic-10', theme: 'sleep', register: 'poetic', length: 10, lang: 'fr' },
  { id: 'fr-sleep-acadian-20', theme: 'sleep', register: 'acadian', length: 20, lang: 'fr' },
  { id: 'fr-stress-plain-5', theme: 'stress', register: 'plain', length: 5, lang: 'fr' },
  { id: 'fr-stress-buddhist-10', theme: 'stress', register: 'buddhist', length: 10, lang: 'fr' },
  { id: 'fr-grief-poetic-10', theme: 'grief', register: 'poetic', length: 10, lang: 'fr' },
  { id: 'fr-walking-plain-5', theme: 'walking', register: 'plain', length: 5, lang: 'fr' },
  { id: 'fr-performance-stoic-3', theme: 'performance', register: 'stoic', length: 3, lang: 'fr' },
  { id: 'fr-gratitude-acadian-5', theme: 'gratitude', register: 'acadian', length: 5, lang: 'fr' },
  { id: 'fr-gratitude-poetic-3', theme: 'gratitude', register: 'poetic', length: 3, lang: 'fr' },
  { id: 'fr-bodyscan-buddhist-10', theme: 'bodyscan', register: 'buddhist', length: 10, lang: 'fr' },

  // ── English ───────────────────────────────────────────────────────────────
  { id: 'en-focus-plain-5', theme: 'focus', register: 'plain', length: 5, lang: 'en' },
  { id: 'en-sleep-poetic-10', theme: 'sleep', register: 'poetic', length: 10, lang: 'en' },
  { id: 'en-stress-plain-5', theme: 'stress', register: 'plain', length: 5, lang: 'en' },
  { id: 'en-performance-stoic-3', theme: 'performance', register: 'stoic', length: 3, lang: 'en' },
  { id: 'en-gratitude-plain-5', theme: 'gratitude', register: 'plain', length: 5, lang: 'en' },
  { id: 'en-bodyscan-buddhist-10', theme: 'bodyscan', register: 'buddhist', length: 10, lang: 'en' },
];

module.exports = { CATALOG };
